#-------------------------------
# General Site Settings
title: Imoye
logo: '../images/logorecorte.png' # You can add own logo. For example '/images/logo.png'.
description: Coletivo de mentorias entre mulheres negras na area de tecnologia
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
blog-theme: light # By default, Atega theme uses a 'light' color scheme, to change the color scheme to dark use 'dark' value (_includes/color-scheme)


#-------------------------------
# Author Settings
# author:
#   name: Imoye
#   image: '../images/logorecorte.png'


#-------------------------------
# Hero Settings
hero:
  hero__title: Oi, Nós somos <span class="hero__name">Imoye</span>.
  hero__job: #Designer, Illustrator
  hero__description: Somos um grupo de mentoria coletiva entre mulheres negras das áreas de tecnologia.
  hero__button__text: Leia sobre nós
  hero__button__link: '/sobre'
  hero__image: 'images/logorecorte.png'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp__title: Fique por dentro das nossas novidades # Add your Title
mailchimp__text: Se increve para ficar por dentro dos nossos posts e novidades. # Add your description.
mailchimp__identifier: https://dev.us1.list-manage.com/subscribe/post?u=3e70e410e7d15aa497bc0e394&amp;id=addb892347 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Inscreva-se # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: mentoria@imoye.dev # Add your email for contant form
  description: #Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Social Links (Footer)
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com/imoye_ig"}
- {icon: "ion-logo-github", link: "https://github.com/imoye-mentoria"}
- {icon: "ion-logo-linkedin", link: "https://linkedin.com"}
#- {icon: "ion-logo-youtube", link: "https://youtube.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-codepen", link: "https://codepen.io"}
#- {icon: "ion-logo-vimeo", link: "https://vimeo.com/"}


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Gallery Footer Section
#gallery:
  # title: Gallery
  # images:
  #   - alt: 'Minimalism'
  #     url: '/images/06.jpg'
  #   - alt: 'Minimalism'
  #     url: '/images/05.jpg'
  #   - alt: 'Minimalism'
  #     url: '/images/08.jpg'
  #   - alt: 'Minimalism'
  #     url: '/images/03.jpg'
  #   - alt: 'Minimalism'
  #     url: '/images/09.jpg'
  #   - alt: 'Minimalism'
  #     url: '/images/04.jpg'


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
